version: '{build}-{branch}'
build: false

branches:
  only:
    - master

cache:
  - '%LOCALAPPDATA%\pip\Cache'

image:
  - Visual Studio 2022

environment:
  matrix:
    - TOXENV: check
      PY_PYTHON: 3.10
    - TOXENV: 'py37-pytest6'
      PY_PYTHON: 3.7
    - TOXENV: 'py37-pytest7'
      PY_PYTHON: 3.7
    - TOXENV: 'py38-pytest6'
      PY_PYTHON: 3.8
    - TOXENV: 'py38-pytest8'
      PY_PYTHON: 3.8
    - TOXENV: 'py39-pytest6'
      PY_PYTHON: 3.9
    - TOXENV: 'py39-pytest8'
      PY_PYTHON: 3.9
    - TOXENV: 'py310-pytest6'
      PY_PYTHON: 3.10
    - TOXENV: 'py310-pytest8'
      PY_PYTHON: 3.10
    - TOXENV: 'py311-pytest6'
      PY_PYTHON: 3.11
    - TOXENV: 'py311-pytest8'
      PY_PYTHON: 3.11
    - TOXENV: 'py312-pytest6'
      PY_PYTHON: 3.12
    - TOXENV: 'py312-pytest8'
      PY_PYTHON: 3.12

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*

install:
  - py --list
  - py -m pip install --upgrade pip
  - py -m pip install tox

test_script:
  - py -m tox

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
