version: '{build}-{branch}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  matrix:
    - TOXENV: check
    - TOXENV: 'py37-pytest{5,6,7,8}'
    - TOXENV: 'py38-pytest{5,6,7,8}'
    - TOXENV: 'py39-pytest{5,6,7,8}'
    - TOXENV: 'py310-pytest{5,6,7,8}'
    - TOXENV: 'py311-pytest{5,6,7,8}'
    - TOXENV: 'py312-pytest{5,6,7,8}'
    - TOXENV: 'py313-pytest{5,6,7,8}'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - C:\Python36\python -m pip install --progress-bar=off tox
test_script:
  - C:\Python36\python -m tox
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
