#!/bin/bash

# Facilitates interactive testing with virtualenv produced by tox.
# Script should be used as '. init-tox-env'.

projectdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
envname="$@"
tox -c ${projectdir} -e ${envname} --notest && source ${projectdir}/.tox/${envname}/bin/activate
