#!/bin/bash

# Facilitates interactive testing with virtualenv produced by tox.
# Script should be used as '. init-tox-env'.

projectdir=`dirname $0`
envname=py27-pytest31
tox -e ${envname} --notest && source ${projectdir}/.tox/${envname}/bin/activate && cd ${projectdir}/tests

