name: test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        name:
          - ubuntu-py310-lintcov
          - ubuntu-py37
          - ubuntu-py38
          - ubuntu-py39
          - ubuntu-py310
          - ubuntu-py311
          - ubuntu-py312
          - ubuntu-pypy3

        include:
          - name: ubuntu-py310-lintcov
            python: "3.10"
            tox_env: check,coverage
            coverage: true
          - name: ubuntu-py37
            python: "3.7"
            tox_env: py37
          - name: ubuntu-py38
            python: "3.8"
            tox_env: py38
          - name: ubuntu-py39
            python: "3.9"
            tox_env: py39
          - name: ubuntu-py310
            python: "3.10"
            tox_env: py310
          - name: ubuntu-py311
            python: "3.11"
            tox_env: py311
          - name: ubuntu-py312
            python: "3.12"
            tox_env: py312
          - name: ubuntu-pypy3
            python: "pypy-3.7"
            tox_env: pypy3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test with tox
      if: "matrix.tox_env"
      run: "tox -e ${{ matrix.tox_env }}"

    - name: Coveralls
      if: "matrix.coverage"
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.lcov
